## 【例4.1】发现缺失数据的常用方法。

In [1]:
import pandas as pd

df = pd.DataFrame({
       'A': [1, 2, None, 4],
       'B': [5, None, 7, 8],
       'C': [9, 10, 11, 12]
   })
print(df.isnull())

       A      B      C
0  False  False  False
1  False   True  False
2   True  False  False
3  False  False  False


In [2]:
print(df.notnull())

       A      B     C
0   True   True  True
1   True  False  True
2  False   True  True
3   True   True  True


In [3]:
 df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   A       3 non-null      float64
 1   B       3 non-null      float64
 2   C       4 non-null      int64  
dtypes: float64(2), int64(1)
memory usage: 224.0 bytes


In [4]:
df.describe()

A         B          C
count  3.000000  3.000000   4.000000
mean   2.333333  6.666667  10.500000
std    1.527525  1.527525   1.290994
min    1.000000  5.000000   9.000000
25%    1.500000  6.000000   9.750000
50%    2.000000  7.000000  10.500000
75%    3.000000  7.500000  11.250000
max    4.000000  8.000000  12.000000

In [5]:
df_interpolated = df.interpolate()

In [6]:
df_interpolated

A    B   C
0  1.0  5.0   9
1  2.0  6.0  10
2  3.0  7.0  11
3  4.0  8.0  12

【例4.2】以下是使用 pandas 和 scikit-learn 库进行数据清洗，包括处理缺失值、重复值和无效值：

In [7]:
import pandas as pd
from sklearn.impute import SimpleImputer

# 创建示例数据
data = {'姓名': ['张三', '李四', '王五', '赵六', '小明'],
        '年龄': [23, 26, None, 24, 25],
        '性别': ['男', '男', '女', '男', None],
        '成绩': [90, 80, 85, 92, None]}
df = pd.DataFrame(data)


In [8]:
df

姓名    年龄    性别    成绩
0  张三  23.0     男  90.0
1  李四  26.0     男  80.0
2  王五   NaN     女  85.0
3  赵六  24.0     男  92.0
4  小明  25.0  None   NaN

In [9]:
df_cleaned = df.dropna()
df['年龄'].fillna(df['年龄'].mean(), inplace=True)
# 用性别列的众数填充性别缺失值
df['性别'].fillna(df['性别'].mode()[0], inplace=True)
# 用成绩列的中位数填充成绩缺失值
df['成绩'].fillna(df['成绩'].median(), inplace=True)


【例4.3】演示对数据的归一化处理。

In [10]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler, MaxAbsScaler
import pandas as pd
import numpy as np

# 创建示例数据
data = pd.DataFrame({'A': [1, 2, 3, 4, 5],
                     'B': [10, 20, 30, 40, 50],
                     'C': [100, 200, 300, 400, 500]})
# StandardScaler 将数据进行标准化处理，使得数据的均值为0，方差为1。
scaler = StandardScaler()
scaled_data = scaler.fit_transform(data)
print("StandardScaler后的数据：\n", scaled_data)
# MinMaxScaler 将数据进行缩放处理，使得数据在指定的范围内。
minmax_scaler = MinMaxScaler(feature_range=(0, 1))
scaled_data = minmax_scaler.fit_transform(data)
print("MinMaxScaler后的数据：\n", scaled_data)

# RobustScaler 与StandardScaler类似，但是可以处理异常值。
robust_scaler = RobustScaler()
scaled_data = robust_scaler.fit_transform(data)
print("RobustScaler后的数据：\n", scaled_data)

# MaxAbsScaler 将数据缩放到[-1,1]的范围内，适用于稀疏数据。
maxabs_scaler = MaxAbsScaler()
scaled_data = maxabs_scaler.fit_transform(data)
print("MaxAbsScaler后的数据：\n", scaled_data)


StandardScaler后的数据：
 [[-1.41421356 -1.41421356 -1.41421356]
 [-0.70710678 -0.70710678 -0.70710678]
 [ 0.          0.          0.        ]
 [ 0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356]]
MinMaxScaler后的数据：
 [[0.   0.   0.  ]
 [0.25 0.25 0.25]
 [0.5  0.5  0.5 ]
 [0.75 0.75 0.75]
 [1.   1.   1.  ]]
RobustScaler后的数据：
 [[-1.  -1.  -1. ]
 [-0.5 -0.5 -0.5]
 [ 0.   0.   0. ]
 [ 0.5  0.5  0.5]
 [ 1.   1.   1. ]]
MaxAbsScaler后的数据：
 [[0.2 0.2 0.2]
 [0.4 0.4 0.4]
 [0.6 0.6 0.6]
 [0.8 0.8 0.8]
 [1.  1.  1. ]]


In [11]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler, MaxAbsScaler
import pandas as pd
import numpy as np

# 创建示例数据
data = pd.DataFrame({'A': [1, 2, 3, 4, 5],
                     'B': [10, 20, 30, 40, 50],
                     'C': [100, 200, 300, 400, 500]})
# StandardScaler 将数据进行标准化处理，使得数据的均值为0，方差为1。
scaler = StandardScaler()
scaled_data = scaler.fit_transform(data)
print("StandardScaler后的数据：\n", scaled_data)
# MinMaxScaler 将数据进行缩放处理，使得数据在指定的范围内。
minmax_scaler = MinMaxScaler(feature_range=(0, 1))
scaled_data = minmax_scaler.fit_transform(data)
print("MinMaxScaler后的数据：\n", scaled_data)

# RobustScaler 与StandardScaler类似，但是可以处理异常值。
robust_scaler = RobustScaler()
scaled_data = robust_scaler.fit_transform(data)
print("RobustScaler后的数据：\n", scaled_data)

# MaxAbsScaler 将数据缩放到[-1,1]的范围内，适用于稀疏数据。
maxabs_scaler = MaxAbsScaler()
scaled_data = maxabs_scaler.fit_transform(data)
print("MaxAbsScaler后的数据：\n", scaled_data)


StandardScaler后的数据：
 [[-1.41421356 -1.41421356 -1.41421356]
 [-0.70710678 -0.70710678 -0.70710678]
 [ 0.          0.          0.        ]
 [ 0.70710678  0.70710678  0.70710678]
 [ 1.41421356  1.41421356  1.41421356]]
MinMaxScaler后的数据：
 [[0.   0.   0.  ]
 [0.25 0.25 0.25]
 [0.5  0.5  0.5 ]
 [0.75 0.75 0.75]
 [1.   1.   1.  ]]
RobustScaler后的数据：
 [[-1.  -1.  -1. ]
 [-0.5 -0.5 -0.5]
 [ 0.   0.   0. ]
 [ 0.5  0.5  0.5]
 [ 1.   1.   1. ]]
MaxAbsScaler后的数据：
 [[0.2 0.2 0.2]
 [0.4 0.4 0.4]
 [0.6 0.6 0.6]
 [0.8 0.8 0.8]
 [1.  1.  1. ]]


【例4.5】L1正则化：

In [12]:
from sklearn.preprocessing import Normalizer
import numpy as np

X = np.array([[1, 2, 3], [4000, 500, 600], [79, 877777, 97]])

transformer = Normalizer(norm='l1')
X_normalized = transformer.transform(X)

print(X_normalized)


[[1.66666667e-01 3.33333333e-01 5.00000000e-01]
 [7.84313725e-01 9.80392157e-02 1.17647059e-01]
 [8.99820378e-05 9.99799534e-01 1.10484274e-04]]


【例4.6】L2正则化。

In [13]:
from sklearn.preprocessing import Normalizer
import numpy as np
X = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

transformer = Normalizer(norm='l2')
X_normalized = transformer.transform(X)

print(X_normalized)


[[0.26726124 0.53452248 0.80178373]
 [0.45584231 0.56980288 0.68376346]
 [0.50257071 0.57436653 0.64616234]]


【例4.7】将['apple', 'banana', 'pear']进行LabelEncoder。

In [14]:
from sklearn.preprocessing import LabelEncoder
# 创建 LabelEncoder 对象
le = LabelEncoder()

# 定义标签列表
labels = ['apple', 'banana', 'pear']

# 使用 LabelEncoder 对标签进行编码
encoded_labels = le.fit_transform(labels)
# 输出编码结果
print(encoded_labels)


[0 1 2]


【例4.8】使用scikit-learn将[“红色”，“蓝色”，“绿色”]进行OneHotEncoder编码。

In [15]:

from sklearn.preprocessing import OneHotEncoder
import numpy as np
# 创建 OneHotEncoder 对象
ohe = OneHotEncoder()
# 定义标签列表
labels = ['红色', '蓝色', '绿色']
# 使用 OneHotEncoder 对标签进行独热编码
encoded_labels = ohe.fit_transform(np.array(labels).reshape(-1, 1)).toarray()
# 输出独热编码结果
print(encoded_labels)


[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]


【例4.9】使用scikit-learn将文本分成单个单词（称为标记），并计算每个标记在文本中出现的频率。

In [16]:

from sklearn.feature_extraction.text import CountVectorizer

corpus = [
    'This is the first document.',
    'This is the second second document.',
    'And the third one.',
    'Is this the first document?',
]
# 创建 CountVectorizer 对象，并拟合文本数据
vectorizer = CountVectorizer()
vectorizer.fit(corpus)

# 转换文本数据
vectorized_corpus = vectorizer.transform(corpus)
# 将稀疏矩阵转换为密集矩阵并打印结果
print(vectorized_corpus.toarray())


[[0 1 1 1 0 0 1 0 1]
 [0 1 0 1 0 2 1 0 1]
 [1 0 0 0 1 0 1 1 0]
 [0 1 1 1 0 0 1 0 1]]


【例4.10】使用TF-IDF对字符串进行编码。

In [17]:
from sklearn.feature_extraction.text import TfidfVectorizer
corpus = [
    'This is the first document.',
    'This is the second second document.',
    'That is also a book!!']
#创建 TfidfVectorizer 对象，并拟合文本数据
vectorizer = TfidfVectorizer()
vectorizer.fit(corpus)

#转换文本数据
vectorized_corpus = vectorizer.transform(corpus)
print(vectorized_corpus)
#将稀疏矩阵转换为密集矩阵并打印结果
print(vectorized_corpus.toarray())


  (0, 8)	0.43306684852870914
  (0, 7)	0.43306684852870914
  (0, 4)	0.33631504064053513
  (0, 3)	0.5694308628404254
  (0, 2)	0.43306684852870914
  (1, 8)	0.3083318691673373
  (1, 7)	0.3083318691673373
  (1, 5)	0.8108387095324792
  (1, 4)	0.23944720188599447
  (1, 2)	0.3083318691673373
  (2, 6)	0.546454011634009
  (2, 4)	0.3227445421804912
  (2, 1)	0.546454011634009
  (2, 0)	0.546454011634009
[[0.         0.         0.43306685 0.56943086 0.33631504 0.
  0.         0.43306685 0.43306685]
 [0.         0.         0.30833187 0.         0.2394472  0.81083871
  0.         0.30833187 0.30833187]
 [0.54645401 0.54645401 0.         0.         0.32274454 0.
  0.54645401 0.         0.        ]]


【例4.11】下面是一个简单的示例代码，演示如何使用VarianceThreshold方法对数据集进行特征选择。

In [18]:

from sklearn.feature_selection import VarianceThreshold
from sklearn.datasets import load_iris

# 加载鸢尾花数据集
iris = load_iris()
X = iris.data
y = iris.target

# 方差选择法，删除方差低于阈值的特征
selector = VarianceThreshold(threshold=0.2)
X_new = selector.fit_transform(X)

# 输出选择后的数据集大小
print(f"原始数据集大小：{X.shape}, 特征选择后的数据集大小：{X_new.shape}")



原始数据集大小：(150, 4), 特征选择后的数据集大小：(150, 3)


【例4.12】卡方检验对数据集属性选择。

In [19]:

from sklearn.datasets import load_iris
from sklearn.feature_selection import SelectKBest, chi2

# 加载鸢尾花数据集
iris = load_iris()
X, y = iris.data, iris.target

# 使用 SelectKBest 方法和卡方检验选择最重要的两个特征
selector = SelectKBest(chi2, k=2)
X_new = selector.fit_transform(X, y)

# 打印选择的特征
print(selector.get_support())
# 打印选择的特征的值
print(X_new[:5])


[False False  True  True]
[[1.4 0.2]
 [1.4 0.2]
 [1.3 0.2]
 [1.5 0.2]
 [1.4 0.2]]


【例4.13】相关系数对数据集属性选择。

In [20]:

from sklearn.datasets import load_breast_cancer
from sklearn.feature_selection import SelectKBest, f_regression

# 加载乳腺癌数据集
cancer = load_breast_cancer()
X, y = cancer.data, cancer.target

# 使用 SelectKBest 方法和相关系数选择与分类目标相关性最高的两个特征
selector = SelectKBest(f_regression, k=3)
X_new = selector.fit_transform(X, y)

# 打印选择的特征
print(selector.get_support())
# 打印选择的特征的值
print(X_new[:5])


[False False False False False False False  True False False False False
 False False False False False False False False False False  True False
 False False False  True False False]
[[1.471e-01 1.846e+02 2.654e-01]
 [7.017e-02 1.588e+02 1.860e-01]
 [1.279e-01 1.525e+02 2.430e-01]
 [1.052e-01 9.887e+01 2.575e-01]
 [1.043e-01 1.522e+02 1.625e-01]]


In [21]:
from sklearn.datasets import load_iris
from sklearn.feature_selection import SelectKBest, chi2

# 加载鸢尾花数据集
iris = load_iris()
X, y = iris.data, iris.target
# 使用 SelectKBest 方法和相关系数选择与分类目标相关性最高的两个特征
print(X[:5])
selector = SelectKBest(f_regression, k=3)
X_new = selector.fit_transform(X, y)

# 打印选择的特征
print(selector.get_support())
# 打印选择的特征的值
print(X_new[:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[ True False  True  True]
[[5.1 1.4 0.2]
 [4.9 1.4 0.2]
 [4.7 1.3 0.2]
 [4.6 1.5 0.2]
 [5.  1.4 0.2]]


【例4.14】Wrapper方法对数据集属性选择。

In [22]:
from sklearn.datasets import load_iris
from sklearn.feature_selection import RFECV
from sklearn.linear_model import LinearRegression

# 加载鸢尾花数据集
iris = load_iris()
X, y = iris.data, iris.target
# 使用 SelectKBest 方法和相关系数选择与分类目标相关性最高的两个特征
print(X[:5])

# 定义线性回归模型
model = LinearRegression()

# 使用 RFECV 方法选择最佳特征子集
selector = RFECV(model, step=1, cv=5)
X_new = selector.fit_transform(X, y)

# 打印选择的特征的数量
print(selector.n_features_)
# 打印选择的特征的编号
print(selector.support_)
# 打印选择的特征的名称
# 打印选择的特征的名称
selected_feature_names = [name for name, selected in zip(iris.feature_names, selector.support_) if selected]
print(selected_feature_names)


[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
3
[ True False  True  True]
['sepal length (cm)', 'petal length (cm)', 'petal width (cm)']


【例4.15】使用 Lasso Regression 进行特征选择的示例代码。

In [23]:

from sklearn.datasets import load_boston
from sklearn.linear_model import Lasso

# 加载波士顿房价数据集
boston = load_boston()
X, y = boston.data, boston.target

# 定义 Lasso 回归模型
model = Lasso(alpha=0.1)

# 使用 Lasso 方法选择最佳特征子集
model.fit(X, y)
selector = model.coef_ != 0

# 打印选择的特征的数量
print(sum(selector))
# 打印选择的特征的名称
print(boston.feature_names[selector])


12
['CRIM' 'ZN' 'INDUS' 'CHAS' 'RM' 'AGE' 'DIS' 'RAD' 'TAX' 'PTRATIO' 'B'
 'LSTAT']


C:\Python\Python310\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np

        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (i.e.
 

In [24]:
from sklearn.datasets import load_diabetes
from sklearn.linear_model import Lasso

# 加载糖尿病数据集
diabetes = load_diabetes()
X, y = diabetes.data, diabetes.target

# 定义 Lasso 回归模型
model = Lasso(alpha=0.1)

# 使用 Lasso 方法选择最佳特征子集
model.fit(X, y)
selector = model.coef_ != 0

# 打印选择的特征的数量

# 打印选择的特征的名称
print(diabetes.feature_names,f'共有{len(diabetes.feature_names)}')
print('从中选择:',sum(selector))
selected_feature_names = [name for name, selected in zip(diabetes.feature_names, selector) if selected]
print('结果:',selected_feature_names)


['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6'] 共有10
从中选择: 7
结果: ['sex', 'bmi', 'bp', 's1', 's3', 's5', 's6']


In [25]:
from sklearn.datasets import load_diabetes
from sklearn.tree import DecisionTreeRegressor

# Load the diabetes dataset as an alternative to load_boston
diabetes = load_diabetes()
X, y = diabetes.data, diabetes.target

# Define a decision tree regression model
model = DecisionTreeRegressor()

# Use the decision tree method to select the best feature subset
model.fit(X, y)
selector = model.feature_importances_ > 0.1

# Print the number of selected features
print(sum(selector))
# Print the names of the selected features
selected_feature_names = [name for name, selected in zip(diabetes.feature_names, selector) if selected]
print(selected_feature_names)


2
['bmi', 's5']


【例4.17】使用 PCA进行特征选择的示例代码。

In [26]:

from sklearn.datasets import load_iris
from sklearn.decomposition import PCA

# 加载鸢尾花数据集
iris = load_iris()
X, y = iris.data, iris.target
print(X.shape)
# 使用PCA进行特征选择
pca = PCA(n_components=2)
X_new = pca.fit_transform(X)

# 打印新数据的形状
print(X_new.shape)


(150, 4)
(150, 2)


【例4.17】使用Kernel PCA进行特征选择的示例代码。

In [27]:

from sklearn.datasets import make_circles
from sklearn.decomposition import KernelPCA

# 生成随机数据集
X, y = make_circles(n_samples=1000, random_state=42, noise=0.1, factor=0.5)

# 使用 Kernel PCA 方法进行特征选择
kpca = KernelPCA(kernel='rbf', n_components=1)
X_new = kpca.fit_transform(X)

# 打印选择的特征
print(X_new[:5])


[[ 0.14175409]
 [ 0.18173951]
 [ 0.30018073]
 [ 0.33842195]
 [-0.60061192]]


【例4.19】使用LDA进行特征选择的示例代码。

In [28]:

from sklearn.datasets import load_iris
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

# 加载 iris 数据集
iris = load_iris()
X, y = iris.data, iris.target

# 定义 LDA 模型
lda = LinearDiscriminantAnalysis(n_components=2)

# 使用 LDA 进行降维
X_lda = lda.fit_transform(X, y)

# 打印降维后的数据形状
print(X.shape,X_lda.shape)


(150, 4) (150, 2)


【例4.19】使用t-SNE进行特征选择的示例代码。
下面是使用t-SNE进行特征选择的示例代码：

In [29]:


from sklearn.datasets import load_iris
from sklearn.manifold import TSNE

# 加载鸢尾花数据集
iris = load_iris()
X, y = iris.data, iris.target

# 使用TSNE进行特征选择
tsne = TSNE(n_components=2, random_state=42)
X_tsne = tsne.fit_transform(X)

# 打印降维后的数据
print(X_tsne[:5])


C:\Python\Python310\lib\site-packages\sklearn\manifold\_t_sne.py:795: FutureWarning: The default initialization in TSNE will change from 'random' to 'pca' in 1.2.
  warnings.warn(
C:\Python\Python310\lib\site-packages\sklearn\manifold\_t_sne.py:805: FutureWarning: The default learning rate in TSNE will change from 200.0 to 'auto' in 1.2.
  warnings.warn(


[[-12.477135 -18.492872]
 [-11.739949 -21.047226]
 [-10.8905   -20.405169]
 [-10.903398 -20.891945]
 [-12.171896 -18.25238 ]]


【例4.20】Isomap计算案例

In [30]:
from sklearn.datasets import load_digits
from sklearn.manifold import Isomap

# 加载 digits 数据集
digits = load_digits()
X, y = digits.data, digits.target

# 定义 Isomap 模型
isomap = Isomap(n_components=2, n_neighbors=10)

# 使用 Isomap 进行降维
X_isomap = isomap.fit_transform(X)

# 打印降维后的数据形状
print(X_isomap.shape)


(1797, 2)
